name: "kafka"

on:
  push:
    branches:
      - main

jobs:
  kafka:
    name: "kafka"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: brianbinbin/tf-kafka-demo
          path: tf-kafka-demo

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ./tf-kafka-demo
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: ./tf-kafka-demo
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        working-directory: ./tf-kafka-demo
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve  -var="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "zookeeper_connect_string=$(terraform output zookeeper_connect_string)" >> $GITHUB_ENV
          echo "bootstrap_brokers_tls=$(terraform output bootstrap_brokers_tls)" >> $GITHUB_ENV
          echo "bootstrap_brokers=$(terraform output bootstrap_brokers)" >> $GITHUB_ENV
          echo "arn=$(terraform output arn)" >> $GITHUB_ENV

      - name: Show private ip
        run: |
          echo "${{ env.zookeeper_connect_string }}"
          echo "${{ env.bootstrap_brokers_tls }}"
          echo "${{ env.bootstrap_brokers }}"
          echo "${{ env.arn }}"



