name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      -uses: kvrhdn/tfe-run@v1
        with:
          # Token used to communicate with the Terraform Cloud API. Must be a user or
          # team api token.
          token: ${{ secrets.TF_API_TOKEN }}

          # Name of the organization on Terraform Cloud. Defaults to the GitHub
          # organization name.
          organization: bian

          # Name of the workspace on Terraform Cloud.
          workspace: tf-aws-benchmark

          # Optional message to use as name of the run.
          message: |
            Run triggered using tfe-run (commit: ${{ github.SHA }})


          # The type of run, allowed options are 'plan', 'apply' and 'destroy'.
          type: apply

          # Whether we should wait for the plan or run to be applied. This will block
          # until the run is finished.
          wait-for-completion: true


        # Optionally, assign this step an ID so you can refer to the outputs from the
        # action with ${{ steps.<id>.outputs.<output variable> }}
        id: tf-aws-benchmark

