name: "Terraform"

on:
  push:
    branches:
      - cluster

jobs:
  terraform:
    name: "kafka client"
    runs-on: ubuntu-latest
    steps:
      - name: run kafka
        run: | 
          sudo apt install openjdk-11-jre-headless
