name: "Terraform"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O /tmp/emqx.zip https://www.emqx.com/zh/downloads/enterprise/4.3.2/emqx-ee-ubuntu18.04-4.3.2-amd64.zip

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: emqx/tf-aws-benchmark
          path: tf-aws-benchmark

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        working-directory: ./tf-aws-benchmark
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: ./tf-aws-benchmark
        id: init
        run: terraform init
      
      - name: Terraform Validate
        working-directory: ./tf-aws-benchmark
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        working-directory: ./tf-aws-benchmark
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -var="private_key=${{ secrets.SSH_PRIVATE_KEY }}" -var="emqx_package=/tmp/emqx.zip"
